#!/bin/bash
#SBATCH --gpus-per-node=1
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=22
#SBATCH --output=bloom
#SBATCH --account=PAA0201

ifconfig
singularity exec --nv /users/PAS1197/osu8727/workspace/transformers-bloom-inference/osc/bloom.sif bash -c "\
export PYTHONNOUSERSITE=1;
export HOME=/tmp/$USER;
cd /users/PAS1197/osu8727/workspace/transformers-bloom-inference;
export TRANSFORMERS_CACHE=/fs/scratch/PAA0201/LLM_models/cache;
export MII_CACHE_PATH=/tmp/$USER/mii_cache;
export TOKENIZERS_PARALLELISM=false;
export MODEL_NAME=bigscience/bloom-7b1;
export DEPLOYMENT_FRAMEWORK=hf_accelerate;
export DTYPE=bf16;
export MAX_INPUT_LENGTH=2048;
export MAX_BATCH_SIZE=4;
export NUM_GPUS=1;
bash start_server.sh
"
