#!/bin/bash
#SBATCH --gpus-per-node=4
#SBATCH --time=24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=44
#SBATCH --output=bloom
#SBATCH --account=PAA0201

ifconfig
singularity exec --nv /users/PAS1197/osu8727/workspace/transformers-bloom-inference/osc/bloom.sif bash -c "\
export PYTHONNOUSERSITE=1;
export HOME=/tmp/$USER;
cd /users/PAS1197/osu8727/workspace/transformers-bloom-inference;
export TRANSFORMERS_CACHE=/fs/scratch/PAA0201/LLM_models/cache;
export MII_CACHE_PATH=/tmp/$USER/mii_cache;
export TOKENIZERS_PARALLELISM=false;
export MODEL_NAME=microsoft/bloom-deepspeed-inference-int8;
export DEPLOYMENT_FRAMEWORK=ds_inference;
export DTYPE=int8;
export MAX_INPUT_LENGTH=2048;
export MAX_BATCH_SIZE=4;
export NUM_GPUS=4;
bash start_server.sh
"
