#!/bin/bash
#SBATCH --gpus-per-node=1
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=22
#SBATCH --output=OPT_30B
#SBATCH --account=PAA0201

ifconfig
SIF_IMAGE=/fs/project/PAA0201/LLM_models/transformers-bloom-inference-new/osc/bloom.sif
singularity exec --nv $SIF_IMAGE bash -c "\
export PYTHONNOUSERSITE=1;
export HOME=/tmp/$USER;
cd /fs/project/PAA0201/LLM_models/transformers-bloom-inference-new;
export TRANSFORMERS_CACHE=/fs/scratch/PAA0201/LLM_models/cache;
export MII_CACHE_PATH=/tmp/$USER/mii_cache;
export TOKENIZERS_PARALLELISM=false;
export MODEL_NAME=facebook/opt-30b;
export DEPLOYMENT_FRAMEWORK=hf_accelerate;
export DTYPE=bf16;
export MAX_INPUT_LENGTH=2048;
export MAX_BATCH_SIZE=256;
export NUM_GPUS=1;
bash start_server.sh
"
